# Generated by Django 4.0.6 on 2022-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
